version: '2'
services:
    laravel:
        image: nutsllc/toybox-laravel:5.2-php7.0-apache
        environment:
            - ALL_PHP_MODULES=enable
            - OPCACHE=disable
            - DB_CONNECTION=mysql
            - MAIL_HOST=mailcatcher
            - MAIL_PORT=1025
        volumes:
            - "./laravel:/var/www/laravel"
        ports:
            - 8080:80
        working_dir: /var/www/laravel

    mariadb:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=familycal
        volumes:
            - "./mariadb:/var/lib/mysql"
        ports:
            - 3306:3306

    mailcatcher:
        image: nutsllc/toybox-mailcatcher:latest
        ports:
            - 1025:1025
            - 1080:1080
