version: '2'
services:
    laravel:
        image: nutsllc/toybox-php:7.0-apache
        environment:
            - ALL_PHP_MODULES=enable
            - OPCACHE=disable
            - DB_CONNECTION=mysql
            - MAIL_HOST=mailcatcher
            - MAIL_PORT=1025
            - PATH=$PATH:/var/www/laravel/vendor/bin
            - DOCUMENT_ROOT=/var/www/laravel/public
        volumes:
            - "./laravel:/var/www/laravel"
        ports:
            - 8080:80
        working_dir: /var/www/laravel

    mariadb:
        image: mysql
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=familycal
        volumes:
            - "./mariadb:/var/lib/mysql"

#    mariadb_testing:
#        image: mysql
#        environment:
#            - MYSQL_ROOT_PASSWORD=root
#            - MYSQL_DATABASE=familycal
#        volumes:
#            - "./mariadb_testing:/var/lib/mysql"

    mailcatcher:
        image: nutsllc/toybox-mailcatcher:latest
        ports:
            - 1025:1025
            - 1080:1080
