version: '2'
services:
    laravel:
        image: nutsllc/toybox-laravel:5.2-php7.0-apache
        environment:
            - ALL_PHP_MODULES=enable
            - OPCACHE=disable
            - DB_CONNECTION=sqlite
            - MAIL_HOST=mailcatcher
            - MAIL_PORT=1025
        volumes:
            - "./laravel:/var/www/laravel"
        ports:
            - 8080:80
        working_dir: /var/www/laravel

    mailcatcher:
        image: nutsllc/toybox-mailcatcher:latest
        ports:
            - 1025:1025
            - 1080:1080
